# 全局设置
Options:
  # 语言
  Language: "zh_CN"
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # OP 版本更新通知
  OP-Notify: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false

# 数据设置
Database:
  # 存储方式 (JSON, SQL, SQLITE)
  Type: SQLITE
  # Json 设置
  JSON:
    file: database.json
  # Sql 设置
  SQL:
    host: localhost
    port: 3306
    user: root
    password: password
    database: minecraft
    table: expboostqwq
  # Sqlite 设置
  SQLITE:
    file: database.db
    table: expboostqwq